class MapModel {
  MapModel(this.key);
  String key;
}

class MapData {
  var data = <MapModel>[
    MapModel("Hartlepool"),
    MapModel("Middlesbrough"),
    MapModel("Redcar and Cleveland"),
    MapModel("Stockton-on-Tees"),
    MapModel("Darlington"),
    MapModel("Halton"),
    MapModel("Warrington"),
    MapModel("Blackburn with Darwen"),
    MapModel("Blackpool"),
    MapModel("Kingston upon Hull, City of"),
    MapModel("East Riding of Yorkshire"),
    MapModel("North East Lincolnshire"),
    MapModel("North Lincolnshire"),
    MapModel("York"),
    MapModel("Derby"),
    MapModel("Leicester"),
    MapModel("Rutland"),
    MapModel("Nottingham"),
    MapModel("Herefordshire, County of"),
    MapModel("Telford and Wrekin"),
    MapModel("Stoke-on-Trent"),
    MapModel("Bath and North East Somerset"),
    MapModel("Bristol, City of"),
    MapModel("North Somerset"),
    MapModel("South Gloucestershire"),
    MapModel("Plymouth"),
    MapModel("Torbay"),
    MapModel("Swindon"),
    MapModel("Peterborough"),
    MapModel("Luton"),
    MapModel("Southend-on-Sea"),
    MapModel("Thurrock"),
    MapModel("Medway"),
    MapModel("Bracknell Forest"),
    MapModel("West Berkshire"),
    MapModel("Reading"),
    MapModel("Slough"),
    MapModel("Windsor and Maidenhead"),
    MapModel("Wokingham"),
    MapModel("Milton Keynes"),
    MapModel("Brighton and Hove"),
    MapModel("Portsmouth"),
    MapModel("Southampton"),
    MapModel("Isle of Wight"),
    MapModel("County Durham"),
    MapModel("Cheshire East"),
    MapModel("Cheshire West and Chester"),
    MapModel("Shropshire"),
    MapModel("Cornwall"),
    MapModel("Isles of Scilly"),
    MapModel("Wiltshire"),
    MapModel("Bedford"),
    MapModel("Central Bedfordshire"),
    MapModel("Northumberland"),
    MapModel("Bournemouth, Christchurch and Poole"),
    MapModel("Dorset"),
    MapModel("Buckinghamshire"),
    MapModel("North Northamptonshire"),
    MapModel("West Northamptonshire"),
    MapModel("Cambridge"),
    MapModel("East Cambridgeshire"),
    MapModel("Fenland"),
    MapModel("Huntingdonshire"),
    MapModel("South Cambridgeshire"),
    MapModel("Allerdale"),
    MapModel("Barrow-in-Furness"),
    MapModel("Carlisle"),
    MapModel("Copeland"),
    MapModel("Eden"),
    MapModel("South Lakeland"),
    MapModel("Amber Valley"),
    MapModel("Bolsover"),
    MapModel("Chesterfield"),
    MapModel("Derbyshire Dales"),
    MapModel("Erewash"),
    MapModel("High Peak"),
    MapModel("North East Derbyshire"),
    MapModel("South Derbyshire"),
    MapModel("East Devon"),
    MapModel("Exeter"),
    MapModel("Mid Devon"),
    MapModel("North Devon"),
    MapModel("South Hams"),
    MapModel("Teignbridge"),
    MapModel("Torridge"),
    MapModel("West Devon"),
    MapModel("Eastbourne"),
    MapModel("Hastings"),
    MapModel("Lewes"),
    MapModel("Rother"),
    MapModel("Wealden"),
    MapModel("Basildon"),
    MapModel("Braintree"),
    MapModel("Brentwood"),
    MapModel("Castle Point"),
    MapModel("Chelmsford"),
    MapModel("Colchester"),
    MapModel("Epping Forest"),
    MapModel("Harlow"),
    MapModel("Maldon"),
    MapModel("Rochford"),
    MapModel("Tendring"),
    MapModel("Uttlesford"),
    MapModel("Cheltenham"),
    MapModel("Cotswold"),
    MapModel("Forest of Dean"),
    MapModel("Gloucester"),
    MapModel("Stroud"),
    MapModel("Tewkesbury"),
    MapModel("Basingstoke and Deane"),
    MapModel("East Hampshire"),
    MapModel("Eastleigh"),
    MapModel("Fareham"),
    MapModel("Gosport"),
    MapModel("Hart"),
    MapModel("Havant"),
    MapModel("New Forest"),
    MapModel("Rushmoor"),
    MapModel("Test Valley"),
    MapModel("Winchester"),
    MapModel("Broxbourne"),
    MapModel("Dacorum"),
    MapModel("Hertsmere"),
    MapModel("North Hertfordshire"),
    MapModel("Three Rivers"),
    MapModel("Watford"),
    MapModel("Ashford"),
    MapModel("Canterbury"),
    MapModel("Dartford"),
    MapModel("Dover"),
    MapModel("Gravesham"),
    MapModel("Maidstone"),
    MapModel("Sevenoaks"),
    MapModel("Folkestone and Hythe"),
    MapModel("Swale"),
    MapModel("Thanet"),
    MapModel("Tonbridge and Malling"),
    MapModel("Tunbridge Wells"),
    MapModel("Burnley"),
    MapModel("Chorley"),
    MapModel("Fylde"),
    MapModel("Hyndburn"),
    MapModel("Lancaster"),
    MapModel("Pendle"),
    MapModel("Preston"),
    MapModel("Ribble Valley"),
    MapModel("Rossendale"),
    MapModel("South Ribble"),
    MapModel("West Lancashire"),
    MapModel("Wyre"),
    MapModel("Blaby"),
    MapModel("Charnwood"),
    MapModel("Harborough"),
    MapModel("Hinckley and Bosworth"),
    MapModel("Melton"),
    MapModel("North West Leicestershire"),
    MapModel("Oadby and Wigston"),
    MapModel("Boston"),
    MapModel("East Lindsey"),
    MapModel("Lincoln"),
    MapModel("North Kesteven"),
    MapModel("South Holland"),
    MapModel("South Kesteven"),
    MapModel("West Lindsey"),
    MapModel("Breckland"),
    MapModel("Broadland"),
    MapModel("Great Yarmouth"),
    MapModel("King's Lynn and West Norfolk"),
    MapModel("North Norfolk"),
    MapModel("Norwich"),
    MapModel("South Norfolk"),
    MapModel("Craven"),
    MapModel("Hambleton"),
    MapModel("Harrogate"),
    MapModel("Richmondshire"),
    MapModel("Ryedale"),
    MapModel("Scarborough"),
    MapModel("Selby"),
    MapModel("Ashfield"),
    MapModel("Bassetlaw"),
    MapModel("Broxtowe"),
    MapModel("Gedling"),
    MapModel("Mansfield"),
    MapModel("Newark and Sherwood"),
    MapModel("Rushcliffe"),
    MapModel("Cherwell"),
    MapModel("Oxford"),
    MapModel("South Oxfordshire"),
    MapModel("Vale of White Horse"),
    MapModel("West Oxfordshire"),
    MapModel("Mendip"),
    MapModel("Sedgemoor"),
    MapModel("South Somerset"),
    MapModel("Cannock Chase"),
    MapModel("East Staffordshire"),
    MapModel("Lichfield"),
    MapModel("Newcastle-under-Lyme"),
    MapModel("South Staffordshire"),
    MapModel("Stafford"),
    MapModel("Staffordshire Moorlands"),
    MapModel("Tamworth"),
    MapModel("Babergh"),
    MapModel("Ipswich"),
    MapModel("Mid Suffolk"),
    MapModel("Elmbridge"),
    MapModel("Epsom and Ewell"),
    MapModel("Guildford"),
    MapModel("Mole Valley"),
    MapModel("Reigate and Banstead"),
    MapModel("Runnymede"),
    MapModel("Spelthorne"),
    MapModel("Surrey Heath"),
    MapModel("Tandridge"),
    MapModel("Waverley"),
    MapModel("Woking"),
    MapModel("North Warwickshire"),
    MapModel("Nuneaton and Bedworth"),
    MapModel("Rugby"),
    MapModel("Stratford-on-Avon"),
    MapModel("Warwick"),
    MapModel("Adur"),
    MapModel("Arun"),
    MapModel("Chichester"),
    MapModel("Crawley"),
    MapModel("Horsham"),
    MapModel("Mid Sussex"),
    MapModel("Worthing"),
    MapModel("Bromsgrove"),
    MapModel("Malvern Hills"),
    MapModel("Redditch"),
    MapModel("Worcester"),
    MapModel("Wychavon"),
    MapModel("Wyre Forest"),
    MapModel("St Albans"),
    MapModel("Welwyn Hatfield"),
    MapModel("East Hertfordshire"),
    MapModel("Stevenage"),
    MapModel("East Suffolk"),
    MapModel("West Suffolk"),
    MapModel("Somerset West and Taunton"),
    MapModel("Bolton"),
    MapModel("Bury"),
    MapModel("Manchester"),
    MapModel("Oldham"),
    MapModel("Rochdale"),
    MapModel("Salford"),
    MapModel("Stockport"),
    MapModel("Tameside"),
    MapModel("Trafford"),
    MapModel("Wigan"),
    MapModel("Knowsley"),
    MapModel("Liverpool"),
    MapModel("St. Helens"),
    MapModel("Sefton"),
    MapModel("Wirral"),
    MapModel("Barnsley"),
    MapModel("Doncaster"),
    MapModel("Rotherham"),
    MapModel("Sheffield"),
    MapModel("Newcastle upon Tyne"),
    MapModel("North Tyneside"),
    MapModel("South Tyneside"),
    MapModel("Sunderland"),
    MapModel("Birmingham"),
    MapModel("Coventry"),
    MapModel("Dudley"),
    MapModel("Sandwell"),
    MapModel("Solihull"),
    MapModel("Walsall"),
    MapModel("Wolverhampton"),
    MapModel("Bradford"),
    MapModel("Calderdale"),
    MapModel("Kirklees"),
    MapModel("Leeds"),
    MapModel("Wakefield"),
    MapModel("Gateshead"),
    MapModel("City of London"),
    MapModel("Barking and Dagenham"),
    MapModel("Barnet"),
    MapModel("Bexley"),
    MapModel("Brent"),
    MapModel("Bromley"),
    MapModel("Camden"),
    MapModel("Croydon"),
    MapModel("Ealing"),
    MapModel("Enfield"),
    MapModel("Greenwich"),
    MapModel("Hackney"),
    MapModel("Hammersmith and Fulham"),
    MapModel("Haringey"),
    MapModel("Harrow"),
    MapModel("Havering"),
    MapModel("Hillingdon"),
    MapModel("Hounslow"),
    MapModel("Islington"),
    MapModel("Kensington and Chelsea"),
    MapModel("Kingston upon Thames"),
    MapModel("Lambeth"),
    MapModel("Lewisham"),
    MapModel("Merton"),
    MapModel("Newham"),
    MapModel("Redbridge"),
    MapModel("Richmond upon Thames"),
    MapModel("Southwark"),
    MapModel("Sutton"),
    MapModel("Tower Hamlets"),
    MapModel("Waltham Forest"),
    MapModel("Wandsworth"),
    MapModel("Westminster"),
    MapModel("Antrim and Newtownabbey"),
    MapModel("Armagh City, Banbridge and Craigavon"),
    MapModel("Belfast"),
    MapModel("Causeway Coast and Glens"),
    MapModel("Derry City and Strabane"),
    MapModel("Fermanagh and Omagh"),
    MapModel("Lisburn and Castlereagh"),
    MapModel("Mid and East Antrim"),
    MapModel("Mid Ulster"),
    MapModel("Newry, Mourne and Down"),
    MapModel("Ards and North Down"),
    MapModel("Clackmannanshire"),
    MapModel("Dumfries and Galloway"),
    MapModel("East Ayrshire"),
    MapModel("East Lothian"),
    MapModel("East Renfrewshire"),
    MapModel("Na h-Eileanan Siar"),
    MapModel("Falkirk"),
    MapModel("Highland"),
    MapModel("Inverclyde"),
    MapModel("Midlothian"),
    MapModel("Moray"),
    MapModel("North Ayrshire"),
    MapModel("Orkney Islands"),
    MapModel("Scottish Borders"),
    MapModel("Shetland Islands"),
    MapModel("South Ayrshire"),
    MapModel("South Lanarkshire"),
    MapModel("Stirling"),
    MapModel("Aberdeen City"),
    MapModel("Aberdeenshire"),
    MapModel("Argyll and Bute"),
    MapModel("City of Edinburgh"),
    MapModel("Renfrewshire"),
    MapModel("West Dunbartonshire"),
    MapModel("West Lothian"),
    MapModel("Angus"),
    MapModel("Dundee City"),
    MapModel("East Dunbartonshire"),
    MapModel("Fife"),
    MapModel("Perth and Kinross"),
    MapModel("Glasgow City"),
    MapModel("North Lanarkshire"),
    MapModel("Isle of Anglesey"),
    MapModel("Gwynedd"),
    MapModel("Conwy"),
    MapModel("Denbighshire"),
    MapModel("Flintshire"),
    MapModel("Wrexham"),
    MapModel("Ceredigion"),
    MapModel("Pembrokeshire"),
    MapModel("Carmarthenshire"),
    MapModel("Swansea"),
    MapModel("Neath Port Talbot"),
    MapModel("Bridgend"),
    MapModel("Vale of Glamorgan"),
    MapModel("Cardiff"),
    MapModel("Rhondda Cynon Taf"),
    MapModel("Caerphilly"),
    MapModel("Blaenau Gwent"),
    MapModel("Torfaen"),
    MapModel("Monmouthshire"),
    MapModel("Newport"),
    MapModel("Powys"),
    MapModel("Merthyr Tydfil"),
  ];
}
